<?php
include_once("shopping_cart.phtml");

if (!empty($params['products'])) {
    ?>
    <ul>
        <?php
        foreach ($params['products'] as $product):
            ?>
            <li>
                <?=$this->viewHelper::productImgTag($product['image_path'], $product['name'])?>
                <?=$product['name']?>
                <?=$product['color']?>
                <?=$this->viewHelper::formatCurrency($product['price_net'])?>

                =>

                <?=$this->viewHelper::formatCurrency($product['price_gross'])?>
                <a href="/product/add/<?=$product['id']?>"><!-- TODO as ajax request-->
                    Add to cart
                </a>
            </li>
        <?php
        endforeach;
        ?>
    </ul>
    <?php
}
