<?php

if (!empty($params['products'])){
    ?>
    <ul>
    <?php
    foreach($params['products'] as $product):
    ?>
        <li><a href="/product/<?=$product['id']?>">
                <?=$this->viewHelper::productImgTag($product['image_path'], $product['name'])?>
                <?=$product['name']?>
                <?=$product['color']?>
                <br />
                <?=$this->viewHelper::formatCurrency($product['price_net'])?>
                 =>
                <?=$this->viewHelper::formatCurrency($product['price_gross'])?>
            </a>
        </li>
    <?php
    endforeach;
    ?>
    </ul>
<?php
}
