<?php
include_once("shopping_cart.phtml");

if (!empty($params['products'])) {
    ?>
    <form action="/" method="post" id="colorForm">
        <select id="colorFilter" name="color">
            <option value="">Select a color</option>
            <option value="red">Red</option>
            <option value="green">Green</option>
            <option value="blue">Blue</option>
            <option value="yellow">Yellow</option>
        </select>
    </form>
    <script type="text/javascript">
        document.getElementById('colorFilter').onchange = function () {
            if (this.value != "") {
                document.getElementById('colorForm').submit();
            }
        };
    </script>
    <ul>
        <?php
        foreach ($params['products'] as $product):
            ?>
            <li>
                <?=$this->viewHelper::productImgTag($product['image_path'], $product['name'])?>
                <?=$product['name']?>
                <?=$product['color']?>
                <?=$this->viewHelper::formatCurrency($product['price_net'])?>

                =>

                <?=$this->viewHelper::formatCurrency($product['price_gross'])?>
                <a href="/product/add/<?=$product['id']?>"><!-- TODO as ajax request-->
                    Add to cart
                </a>
            </li>
        <?php
        endforeach;
        ?>
    </ul>
    <?php
}
