<!DOCTYPE html>
<html>
<head>
    <title>Defcon shop</title>
    <link href='/assets/css/layout.css' rel='stylesheet' type='text/css'>
</head>
<body>

<nav>
    <a href="/"><img src="http://placekitten.com/300/150" alt="Home" title="Home"/></a><br/>
    <a href="/register">Register</a><br/>
    <a href="/login">Login</a><br/>
    <a href="/logout">Logout</a><br/>
    <a href="/checkout">Checkout</a>
</nav>
<!-- TODO hidde irrelevant links -->
<?php
include_once($includeFile);
?>
</body>
</html>