<?php require("_printFormErrors.phtml"); ?>
<form action="/register" method="post" class="register">
    <label>Email: <input type="email" name="email" required/></label>
    <label>Name: <input type="text" name="name"/></label>
    <!--without required, to demonstrate server side data validation -->
    <label>Password: <input type="password" name="password1" required/></label>
    <label>Repeat Password: <input type="password" name="password2" required/></label>
    <input type="submit" value="Register"/>
</form>