<?php
if (!empty($params['errors'])) {
    ?>
    <ul>
        <?php
        foreach ($params['errors'] as $error) {
            if (is_array($error)) {
                $error = implode(",", $error);
            }
            ?>
            <li><?= $error ?></li>
            <?php
        }
        ?>
    </ul>
    <?php
}
?>
<form action="" method="POST" class="register">
    <label>Email: <input type="email" name="email"/></label>
    <label>Password: <input type="password" name="password1"/></label>
    <label>Repeat Password: <input type="password" name="password2"/></label>
    <input type="submit" value="Register"/>
</form>