<div style="float:right">
    The shopping cart:
    <?php
    if (!empty($params['cart'])):?>
        <ul>
            <?php
            foreach ($params['cart'] as $product):?>
                <li><?= $this->viewHelper::productImgTag($product['image_path'], $product['name']) ?><?= $product['count'] ?></li>
            <?php
            endforeach;
            ?>
        </ul>
    <?php
    endif;
    ?>
</div>
